import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const tactic = localFont({
  src: [
    {
      path: "../../public/TacticSans-BlkIt.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-tactic",
});

export const metadata: Metadata = {
  title: "Match Traker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${tactic.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

